#!/bin/bash

#set -x
set -e

# starts simple writing environment for simple .md -> pdf

header=$(cat <<EOF
---
papersize: A4
fontsize: 12pt
documentclass: scrartcl
geometry: margin=2cm, bottom=3cm
numbersections: true
urlcolor: blue
header-includes:
- \usepackage{soul}
- \usepackage{hyperref}
- \usepackage[dvipsnames]{xcolor}
- \usepackage{scrlayer-scrpage}
- \usepackage{lastpage}
- \usepackage{fontspec}
# - \usepackage[german]{babel}
---

\setmainfont{OpenSans}

\newcommand{\shortauthor}{hvw}
\newcommand{\headerdate}{YYYY-MM-DD}
\renewcommand{\thesubsection}{\arabic{subsection}}

\lohead[\small \shortauthor / \headerdate]{\small \shortauthor / \headerdate}
\cfoot{\thepage\ / \pageref*{LastPage}}
\pagestyle{scrheadings}

# The Title {-}

EOF
)

date=$(date +%F)
header=$(echo "$header" |sed s/YYYY-MM-DD/$date/g)

basename=$1
if [[ ! -f "$basename.md" ]]; then
    echo "$header" > "$basename.md"
    echo "created $basename.md"
fi

pandoc --pdf-engine=lualatex -t latex -o "$basename.pdf" "$basename.md" && evince "$basename.pdf" &
echo "$basename.md" |entr pandoc --pdf-engine=lualatex -t latex -o "$basename.pdf" "$basename.md" \
   -f markdown+escaped_line_breaks+fancy_lists+definition_lists+simple_tables+footnotes+header_attributes
